name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      greetee:
        default: "World"
        description: "Greet this guy"
        required: true
        type: "string"

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ inputs.greetee }}"


  goodbye:
    runs-on: ubuntu-latest
    needs: [ "hello" ]
    steps:
      - run: echo "Goodbye"
      - run: |
          export VARIABLE=$(echo '{"data":{"VARIABLE":"QUxMIEdPT0Q="}}' | jq -r '.data["VARIABLE"] | @base64d')
          echo "$VARIABLE"
          echo '{"status":"UP"}' | yq -P
      - run: >
          echo
          and
          I
          mean
          it.

            
